[WIFI]
MOT_DE_PASSE_WIFI = "Secret123!"
DUREE_SESSION_MINUTES = 480
ISOLATION_INVITES = true

; CHOISISSEZ VOTRE ROUTEUR ICI : iptables, mikrotik, unifi, pfsense
TYPE_ROUTEUR = "iptables" 

[ADMIN]
MOT_DE_PASSE_ADMIN = "AdminPortal2026!"

[API_UNIFI]
UNIFI_URL = "https://127.0.0.1:8443"
UNIFI_USER = "admin"
UNIFI_PASS = "password"
UNIFI_SITE = "default"

[API_MIKROTIK]
MIKROTIK_IP = "192.168.88.1"
MIKROTIK_USER = "admin"
MIKROTIK_PASS = ""